# OC_MDD-P6

###
# group: Auth
# @name Se connecter
POST {{MDD_API_URL}}/auth/login
Content-Type: application/json

{
  "identifier": "user@example.com",
  "password": "password"
}

> {%
    client.global.set("MDD_BEARER_TOKEN", response.body.bearer);
    client.global.set("MDD_REFRESH_TOKEN", response.body.refresh);
%}

###
# group: Auth
# @name Récupérer un refresh token
POST {{MDD_API_URL}}/auth/refresh-token
Authorization: Bearer {{MDD_BEARER_TOKEN}}
Content-Type: application/json

{
    "refreshToken": "{{MDD_REFRESH_TOKEN}}"
}

> {%
    client.global.set("MDD_BEARER_TOKEN", response.body.bearer);
    client.global.set("MDD_REFRESH_TOKEN", response.body.refresh);
%}

###
# group: Auth
# @name S'inscrire
POST {{MDD_API_URL}}/auth/register
Content-Type: application/json

{
  "username": "user2",
  "email": "user2@example.com",
  "password": "password"
}

###
# group: Auth
# @name Récupérer son profile
GET {{MDD_API_URL}}/auth/me
Authorization: Bearer {{MDD_BEARER_TOKEN}}

###
# group: Auth
# @name Se déconnecter
POST {{MDD_API_URL}}/auth/disconnect
Authorization: Bearer {{MDD_BEARER_TOKEN}}

###
# group: User
# @name Modifier ses infos
PUT {{MDD_API_URL}}/users
Authorization: Bearer {{MDD_BEARER_TOKEN}}
Content-Type: application/json

{
  "email": "user3@example.com",
  "username": "user"
}

###
# group: Article
# @name Créer un article
POST {{MDD_API_URL}}/articles
Authorization: Bearer {{MDD_BEARER_TOKEN}}
Content-Type: application/json

{
  "title": "Titre de l'article",
  "content": "Contenu de l'article",
  "theme": {
    "id": 1
  },
  "author": {
    "id": 9
  }
}

###
# group: Article
# @name Créer un commentaire
POST {{MDD_API_URL}}/articles/{{MDD_ARTICLE_ID}}/comments
Authorization: Bearer {{MDD_BEARER_TOKEN}}
Content-Type: application/json

{
  "content": "Mon nouveau commentaire Content: lorem ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled...",
  "author": {
    "id": 1
  }
}

###
# group: Article
# @name Récupérer des commentaires d'un article
GET {{MDD_API_URL}}/articles/{{MDD_ARTICLE_ID}}/comments
Authorization: Bearer {{MDD_BEARER_TOKEN}}

###
# group: Article
# @name Récupérer les articles
GET {{MDD_API_URL}}/articles
Authorization: Bearer {{MDD_BEARER_TOKEN}}

###
# group: Article
# @name Récupérer un article
GET {{MDD_API_URL}}/articles/1
Authorization: Bearer {{MDD_BEARER_TOKEN}}

###
# group: Theme
# @name Récupérer les thèmes
GET {{MDD_API_URL}}/themes
Authorization: Bearer {{MDD_BEARER_TOKEN}}

###
# group: Theme
# @name Récupérer les thèmes d'un utilisateur
GET {{MDD_API_URL}}/themes/subscriptions
Authorization: Bearer {{MDD_BEARER_TOKEN}}

###
# group: Theme
# @name Enregistrer un abonnement
POST {{MDD_API_URL}}/themes/{{MDD_THEME_ID}}/users/{{MDD_USER_ID}}
Authorization: Bearer {{MDD_BEARER_TOKEN}}

###
# group: Theme
# @name Supprimer un abonnment
DELETE {{MDD_API_URL}}/themes/{{MDD_THEME_ID}}/users/{{MDD_USER_ID}}
Authorization: Bearer {{MDD_BEARER_TOKEN}}